repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.1
  hooks:
    - id: terraform_fmt
    - id: terragrunt_fmt
    - id: terraform_tflint
      args:
        - --args=--disable-rule=terraform_comment_syntax
        - --args=--ignore-module=est/vpc-live_v2
        - --args=--disable-rule=terraform_deprecated_index
        - --args=--disable-rule=terraform_deprecated_interpolation
        - --args=--disable-rule=terraform_deprecated_lookup
        - --args=--disable-rule=terraform_documented_outputs
        - --args=--disable-rule=terraform_documented_variables
        - --args=--disable-rule=terraform_empty_list_equality
        # - --args=--disable-rule=terraform_map_duplicate_keys
        - --args=--disable-rule=terraform_module_pinned_source
        - --args=--disable-rule=terraform_module_version
        - --args=--disable-rule=terraform_naming_convention
        - --args=--disable-rule=terraform_required_providers
        - --args=--disable-rule=terraform_required_version
        - --args=--disable-rule=terraform_standard_module_structure
        - --args=--disable-rule=terraform_typed_variables
        - --args=--disable-rule=terraform_unused_declarations
        - --args=--disable-rule=terraform_unused_required_providers
        - --args=--disable-rule=terraform_workspace_remote
